function PSMlabl(figInfo,subtitleL,subtitleR,PrintPlot)

% PSMLABL:  Annotates Ringdown Analysis Tool plots using PSM tools format
%
% Places PSM tools style titles on plots generated by the BPA/PNNL Ringdown
% Analysis Tool.  This function should be called directly by the tool using
% the 'opts' input to the tool.
%
% Usage:
%
%            PSMlabl(figInfo,subtitleL,subtitleR,PrintPlot);
%
% where
%
%   figInfo   = Structure containing information about the generated plot.
%
%   subtitleL = Left justified text to be placed below main title.
%
%   subtitleR = Right justified text to be placed below main title.

% By Jeff M. Johnson, Pacific Northwest National Laboratory.
% Date : March 1999
%
% Copyright (c) 1995-2002 Battelle Memorial Institute.  The Government
% retains a paid-up nonexclusive, irrevocable worldwide license to
% reproduce, prepare derivative works, perform publicly and display
% publicly by or for the Government, including the right to distribute
% to other Government contractors.
%
% Last Update:  January 24, 2002 (JMJ)

if nargin<4; PrintPlot=0; end
if nargin<3; subtitleR=''; end
if nargin<2; subtitleL=''; end

% assignin('base','figInfo',figInfo);
% assignin('base','subtitleL',subtitleL);
% assignin('base','subtitleR',subtitleR);

axesHndls=figInfo.axesHndls; nnaxes=length(axesHndls);
sigtitles=figInfo.titles; nnsigs=length(sigtitles);

if nnaxes==1
  plottype=figInfo.plottypes;
else
  plottype=figInfo.plottypes{1};
end

% Set axes font properties to MATLAB defaults.
fntname=get(0,'DefaultAxesFontName'); fntsize=get(0,'DefaultAxesFontSize');
h=get(axesHndls,{'XLabel' 'YLabel'}); set([h{:}],'FontName',fntname,'FontSize',fntsize);

% Set tick mark direction outward. Remove top and right side tick marks.
if ~strcmp(plottype,'mtbl')
  set(axesHndls,'Box','off','TickDir','out');
  for ii=1:nnaxes
    axesHndl=axesHndls(ii); axes(axesHndl);
    xlim=get(axesHndl,'XLim'); ylim=get(axesHndl,'YLim');
    line([xlim(1); xlim(2); xlim(2)],[ylim(2); ylim(2); ylim(1)], ...
      'Color',get(axesHndl,'XColor'),'LineWidth',get(axesHndl,'LineWidth'));
  end
end

% Add the title and subtitles
if nnsigs==2; if strcmp(sigtitles{2},'Model'); nnsigs=1; end; end

if nnsigs==1
  switch plottype
    case 'tr',  fstr='%s';
    case {'frm', 'frp'}, fstr='Frequency spectrum of %s';
    case 'mtbl', fstr='Modes identified from %s';
    otherwise, fstr='';
  end
else
  fstr='';
end

if isempty(fstr)
  pagetitle=get(get(axesHndls(1),'Title'),'String');
else
  pagetitle=sprintf(fstr,sigtitles{1});
end

titlHndl=get(axesHndls(1),'Title');
set(titlHndl,'FontSize',fntsize+2,'Units','normalized');
if isempty(subtitleL) & isempty(subtitleR)
  set(titlHndl,'String',pagetitle);
else
  set(titlHndl,'String',{pagetitle ' '});
  set(axesHndls(1),'DefaultTextUnits','normalized', ...
    'DefaultTextFontName',fntname, ...
    'DefaultTextFontSize',fntsize, ...
    'DefaultTextVerticalAlignment','baseline');

  titlExtent=get(titlHndl,'Extent'); axes(axesHndls(1));
  text(0,titlExtent(2),subtitleL,'HorizontalAlignment','left');
  text(1,titlExtent(2),subtitleR,'HorizontalAlignment','right');
end

if PrintPlot; print -f; end